apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-demo
  template:
    metadata:
      labels:
        app: vault-demo
    spec:
      containers:
      - name: vault-demo
        image: nginx
        env:
        - name: DB_USER
          value: <path:secret/data/argocd/test-secret#username>
        - name: DB_PASSWORD
          value: <path:secret/data/argocd/test-secret#password>
